server:
  port: 8081
spring:
  thymeleaf:
    check-template-location: false
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization?&serverTimezone=UTC
    username: postgres
    password: postgres
